name: Simple CI

on: [pull_request]

jobs:
  run-ci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm install
    - name: Check if the git repository is clean
      run: $(exit $(git status --porcelain --untracked-files=no | head -255 | wc -l)) || (echo "Dirty git tree"; git diff; exit 1)
    - run: npm run lint
  clang:
    name: Clang-Format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'ios'
          - 'android'
    steps:
    - uses: actions/checkout@v4
    - uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '17'
        include-regex: '^.*(\.h|\.m|\.java)'